### ISSUE TITLE
Ignore some unroutable addresses

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/httpseed#1]
@jonasschnelli has a patch for sipa's seeder here: https://github.com/jonasschnelli/bitcoin-seeder/commit/4abf94b12baa62b1da60c0129c754f3f20171268

Maybe it should be ported to Cartographer?

**Comment by jonasschnelli** [comment]
Mind that the patch (maybe only) works for Hezner data enter. It's a big hack and not all invalid unroutable IP ranges are included... But with this patch at least make the seeder act the jeep below the threshold of hetzners abuse-checker.

**Comment by mikehearn** [comment]
Hah. How did you figure out the list of IP ranges they are looking for? Have you tested that and found it makes Hetzner happy?

I have some partial code that calculates every unrouteable region on the public internet. So it's a more robust solution, but also, not finished :)

**Comment by jonasschnelli** [comment]
Heh. I did wait for serval abusal report mails and grabbed out the most obvious IP ranges (check them against a w3c rfc for some private ip ranges).
Your solution sounds good... As said. My interest was just to keep the seeder running...

**Comment by schildbach** [comment]
I did not get any abuse warning again just by deploying this check:

```
        if (address is Inet4Address) {
            val a0 = UnsignedBytes.toInt(address.address[0])
            if (a0 >= 240) // Reserved for future use
                return false
        }
        return true
```

So I'm closing this now. Thanks to everyone involved.
